package com.santander_tc.reglasnegocioretotc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Proceso implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Proceso() {
    }




}